$(document).ready(function() {

    $(".learning").click(function(){
        $(".learning").addClass("active")
        $(".technology").removeClass("active")
        $(".communication").removeClass("active")
        $("#technology-arrow").removeClass("active")
        $("#learning-arrow").addClass("active")
        $("#communication-arrow").removeClass("active")
        $("#technology-text").removeClass("active")
        $("#learning-text").addClass("active")
        $("#communication-text").removeClass("active")
        $("#technology-dot").removeClass("active")
        $("#learning-dot").addClass("active")
        $("#communication-dot").removeClass("active")
        $("#technology-image").removeClass("active")
        $("#learning-image").addClass("active")
        $("#communication-image").removeClass("active")
    });

    $(".technology").click(function(){
        $(".technology").addClass("active")
        $(".learning").removeClass("active")
        $(".communication").removeClass("active")
        $("#technology-arrow").addClass("active")
        $("#learning-arrow").removeClass("active")
        $("#communication-arrow").removeClass("active")
        $("#technology-text").addClass("active")
        $("#learning-text").removeClass("active")
        $("#communication-text").removeClass("active")
        $("#technology-dot").addClass("active")
        $("#learning-dot").removeClass("active")
        $("#communication-dot").removeClass("active")
        $("#technology-image").addClass("active")
        $("#learning-image").removeClass("active")
        $("#communication-image").removeClass("active")
    });

    $(".communication").click(function(){
        $(".communication").addClass("active")
        $(".learning").removeClass("active")
        $(".technology").removeClass("active")
        $("#technology-arrow").removeClass("active")
        $("#learning-arrow").removeClass("active")
        $("#communication-arrow").addClass("active")
        $("#technology-text").removeClass("active")
        $("#learning-text").removeClass("active")
        $("#communication-text").addClass("active")
        $("#technology-dot").removeClass("active")
        $("#learning-dot").removeClass("active")
        $("#communication-dot").addClass("active")
        $("#technology-image").removeClass("active")
        $("#learning-image").removeClass("active")
        $("#communication-image").addClass("active")
    });
  });